base:
    # Update this value to the location you want the node to store its database
    data_dir: "/Users/ppoliani/aptos-node-testnet"
    role: "full_node"
    waypoint:
        # Update this value to that which the blockchain publicly provides. Please regard the directions
        # below on how to safely manage your genesis_file_location with respect to the waypoint.
        from_file: "./config/waypoint.txt"

execution:
    # Update this to the location to where the genesis.blob is stored, prefer fullpaths
    # Note, this must be paired with a waypoint. If you update your waypoint without a
    # corresponding genesis, the file location should be an empty path.
    genesis_file_location: "./genesis.blob"

full_node_networks:
    - discovery_method: "onchain"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6191"
      network_id: "public"
      mutual_authentication: false
      # Define the upstream peers to connect to
      seed_addrs:
        0f5e83c2030ee771b87c892ce79eba6851d88e714749fd82a8730694a3afd48d:
            - "/ip4/127.0.0.1/tcp/6181/noise-ik/3e7a91da97ebe61451410578244065c87458b055a4c2d68729245b6d2d2e7e00/handshake/0"
          # role: "Validator"
          
state_sync:
  state_sync_driver:
    bootstrapping_mode: ExecuteTransactionsFromGenesis
    continuous_syncing_mode: ExecuteTransactions
api:
    enabled: true
    address: 127.0.0.1:8090
inspection_service:
    address: 0.0.0.0
    port: 9111
    expose_configuration: false
    expose_system_information: true
storage:
  backup_service_address: "127.0.0.1:6196"
